export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_PRODUCT_TO_CART = 'DELETE_PRODUCT_TO_CART';
export const UPDATE_QUANTITY_PRODUCT_TO_CART = 'UPDATE_QUANTITY_PRODUCT_TO_CART';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';